services:
  berghain-haproxy:
    build: .
    ports:
      - "8080:8080" # Expose the backend service
    volumes:
      - ./examples/haproxy/haproxy.cfg:/app/haproxy.cfg
      - ./examples/haproxy/berghain.cfg:/app/examples/haproxy/berghain.cfg
      - ./examples/haproxy/maps/bypass-hosts.lst:/app/examples/haproxy/maps/bypass-hosts.lst:ro
      - reputation-data:/app/examples/haproxy/state
      - ./cmd/spop/config.yaml:/app/config.yaml

volumes:
  reputation-data:
