// Command feedupdater refreshes the HAProxy map/ACL files that Berghain uses
// for IP reputation and network classification (Cloudflare ranges, Tor exit
// nodes, ...). It fetches public feeds and writes each map atomically.
//
// Berghain itself stays stateless: this tool runs out-of-band (cron / systemd
// timer / sidecar) and only produces flat files that HAProxy consults. A
// running HAProxy loads maps at startup, so apply refreshed files with a
// reload, or push them into the running process via the Runtime API admin
// socket (see examples/haproxy/haproxy.cfg).
package main

import (
	"bufio"
	"flag"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// source describes one feed: where to fetch it and how to turn each fetched
// line into an output line (returning "" skips the line).
type source struct {
	name    string
	urls    []string
	outFile string
	parse   func(line string) string
}

var sources = []source{
	{
		name:    "cloudflare",
		urls:    []string{"https://www.cloudflare.com/ips-v4", "https://www.cloudflare.com/ips-v6"},
		outFile: "cloudflare-ips.lst",
		parse:   cidrOnly,
	},
	{
		name:    "tor_exit",
		urls:    []string{"https://check.torproject.org/torbulkexitlist"},
		outFile: "tor_exit.map",
		parse:   ipToMapEntry,
	},
}

// cidrOnly keeps non-comment, non-empty lines verbatim (they are already CIDRs).
func cidrOnly(line string) string {
	line = strings.TrimSpace(line)
	if line == "" || strings.HasPrefix(line, "#") {
		return ""
	}
	return line
}

// ipToMapEntry turns a bare IP into a "<ip> 1" map entry.
func ipToMapEntry(line string) string {
	ip := strings.TrimSpace(line)
	if ip == "" || strings.HasPrefix(ip, "#") {
		return ""
	}
	return ip + " 1"
}

func fetch(client *http.Client, url string) (string, error) {
	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		return "", err
	}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("unexpected status %d", resp.StatusCode)
	}
	// Cap the read so a misbehaving feed cannot exhaust memory.
	b, err := io.ReadAll(io.LimitReader(resp.Body, 64<<20))
	if err != nil {
		return "", err
	}
	return string(b), nil
}

func parseLines(body string, parse func(string) string) []string {
	var out []string
	sc := bufio.NewScanner(strings.NewReader(body))
	sc.Buffer(make([]byte, 0, 64*1024), 1<<20)
	for sc.Scan() {
		if line := parse(sc.Text()); line != "" {
			out = append(out, line)
		}
	}
	return out
}

// writeAtomic writes lines to path via a temp file + rename so readers never
// observe a partially written map.
func writeAtomic(path string, lines []string) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".feedupdater-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)

	w := bufio.NewWriter(tmp)
	fmt.Fprintln(w, "# Generated by cmd/feedupdater — do not edit by hand.")
	for _, l := range lines {
		fmt.Fprintln(w, l)
	}
	if err := w.Flush(); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

func (s source) update(client *http.Client, mapsDir string) error {
	var lines []string
	for _, u := range s.urls {
		body, err := fetch(client, u)
		if err != nil {
			return fmt.Errorf("fetch %s: %w", u, err)
		}
		lines = append(lines, parseLines(body, s.parse)...)
	}
	if len(lines) == 0 {
		// Never overwrite a good map with an empty one on a bad fetch.
		return fmt.Errorf("no entries parsed")
	}
	return writeAtomic(filepath.Join(mapsDir, s.outFile), lines)
}

func run(client *http.Client, mapsDir string) {
	for _, s := range sources {
		if err := s.update(client, mapsDir); err != nil {
			slog.Error("feed update failed", "source", s.name, "error", err)
			continue
		}
		slog.Info("feed updated", "source", s.name, "file", filepath.Join(mapsDir, s.outFile))
	}
}

func main() {
	var (
		mapsDir  string
		interval time.Duration
	)
	flag.StringVar(&mapsDir, "maps-dir", "examples/haproxy/maps", "directory to write map/ACL files into")
	flag.DurationVar(&interval, "interval", 0, "refresh interval (e.g. 6h); 0 runs once and exits")
	flag.Parse()

	client := &http.Client{Timeout: 30 * time.Second}

	run(client, mapsDir)
	if interval <= 0 {
		return
	}
	slog.Info("feedupdater running on a schedule", "interval", interval.String())
	for range time.Tick(interval) {
		run(client, mapsDir)
	}
}
