package reputation

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"net/http"
	"net/netip"
	"os"
	"path/filepath"
	"strings"
	"time"

	"log/slog"

	"github.com/DropMorePackets/berghain/internal/peerserver"
)

// cidrSource is a feed of CIDRs written verbatim to an ACL/map file.
// Stick-tables key on exact addresses, so prefix feeds must stay files.
type cidrSource struct {
	name    string
	urls    []string
	outFile string
}

var cidrSources = []cidrSource{
	{
		name:    "cloudflare",
		urls:    []string{"https://www.cloudflare.com/ips-v4", "https://www.cloudflare.com/ips-v6"},
		outFile: "cloudflare-ips.lst",
	},
}

// ipSource is a feed of individual IPs served over the peers protocol.
type ipSource struct {
	name   string
	urls   []string
	action uint32
}

var torExitSource = ipSource{
	name:   "tor_exit",
	urls:   []string{"https://check.torproject.org/torbulkexitlist"},
	action: actionChallenge,
}

func (s *Service) fetch(ctx context.Context, url string) (string, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return "", err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("unexpected status %d", resp.StatusCode)
	}
	b, err := io.ReadAll(io.LimitReader(resp.Body, 64<<20))
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// cidrOnly keeps non-comment, non-empty lines verbatim (they are already CIDRs).
func cidrOnly(line string) string {
	line = strings.TrimSpace(line)
	if line == "" || strings.HasPrefix(line, "#") {
		return ""
	}
	return line
}

func parseLines(body string, parse func(string) string) []string {
	var out []string
	sc := bufio.NewScanner(strings.NewReader(body))
	sc.Buffer(make([]byte, 0, 64*1024), 1<<20)
	for sc.Scan() {
		if line := parse(sc.Text()); line != "" {
			out = append(out, line)
		}
	}
	return out
}

// parseIPs parses one IP per line, skipping comments and blanks.
func parseIPs(body string) []netip.Addr {
	var out []netip.Addr
	sc := bufio.NewScanner(strings.NewReader(body))
	sc.Buffer(make([]byte, 0, 64*1024), 1<<20)
	for sc.Scan() {
		s := strings.TrimSpace(sc.Text())
		if s == "" || strings.HasPrefix(s, "#") {
			continue
		}
		if a, err := netip.ParseAddr(s); err == nil {
			out = append(out, a)
		}
	}
	return out
}

// writeAtomic writes lines to path via a temp file + rename.
func writeAtomic(path string, lines []string) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".feedupdater-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)

	w := bufio.NewWriter(tmp)
	fmt.Fprintln(w, "# Generated by berghain reputation feeds — do not edit by hand.")
	for _, l := range lines {
		fmt.Fprintln(w, l)
	}
	if err := w.Flush(); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

func (s *Service) updateCIDR(ctx context.Context, src cidrSource) error {
	var lines []string
	for _, u := range src.urls {
		body, err := s.fetch(ctx, u)
		if err != nil {
			return fmt.Errorf("fetch %s: %w", u, err)
		}
		lines = append(lines, parseLines(body, cidrOnly)...)
	}
	if len(lines) == 0 {
		return fmt.Errorf("no entries parsed")
	}
	return writeAtomic(filepath.Join(s.cfg.MapsDir, src.outFile), lines)
}

// refreshStatic fetches the URL feeds and the optional banlist into the
// "static" source and rewrites the CIDR map files.
func (s *Service) refreshStatic(ctx context.Context) {
	if s.cfg.MapsDir != "" {
		for _, src := range cidrSources {
			if err := s.updateCIDR(ctx, src); err != nil {
				slog.ErrorContext(ctx, "cidr feed update failed", "source", src.name, "error", err)
				continue
			}
			slog.InfoContext(ctx, "cidr feed updated", "source", src.name,
				"file", filepath.Join(s.cfg.MapsDir, src.outFile))
		}
	}

	entries := make(map[netip.Addr]peerserver.Entry)

	if s.cfg.TorExits == nil || *s.cfg.TorExits {
		for _, u := range torExitSource.urls {
			body, err := s.fetch(ctx, u)
			if err != nil {
				slog.ErrorContext(ctx, "feed fetch failed", "source", torExitSource.name, "url", u, "error", err)
				continue
			}
			for _, a := range parseIPs(body) {
				entries[a.Unmap()] = peerserver.Entry{Value: torExitSource.action}
			}
		}
	}

	if s.cfg.Banlist != "" {
		b, err := os.ReadFile(s.cfg.Banlist)
		if err != nil {
			slog.ErrorContext(ctx, "reading banlist", "path", s.cfg.Banlist, "error", err)
		} else {
			for _, a := range parseIPs(string(b)) {
				entries[a.Unmap()] = peerserver.Entry{Value: actionBlock} // blocks override challenges
			}
		}
	}

	s.setSource("static", entries)
}

func (s *Service) staticFeedLoop(ctx context.Context) {
	t := time.NewTicker(s.cfg.Interval)
	defer t.Stop()

	s.refreshStatic(ctx)
	for {
		select {
		case <-ctx.Done():
			return
		case <-t.C:
			s.refreshStatic(ctx)
		}
	}
}
